---

- name: Configure OSP network
  sudo: yes
  hosts:
    - tag_osp_network

  vars_files:
    - vars/elasticsearch.yml

  roles:
    - common
    - nodejs
    - elasticsearch
    - nginx
    - supervisor
